groups:
- name: cosmic.rules
  rules:
  - alert: ConsensusFailureHigh
    expr: consensus_failure_rate > 0.05
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "High consensus failure rate"
      
  - alert: RLConvergenceIssue
    expr: rl_convergence_rate < 0.02
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "RL convergence rate below threshold"
